In [74]:
import os
import json
import h5py
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Video
import imageio
from statistics import mean
import robomimic.utils.file_utils as FileUtils
from PIL import Image, ImageDraw, ImageFont
import zarr
from diffusion_policy.common.replay_buffer import ReplayBuffer
from filelock import FileLock
from diffusion_policy.codecs.imagecodecs_numcodecs import register_codecs, Jpeg2k
import pdb
from tqdm import tqdm

In [ ]:
data = h5py.File('all_robomimic_data_combined.hdf5', 'r')

In [79]:
for i in tqdm([0]): #tqdm([120,156,167,176]):
    video_path = os.path.join('.', f"temp{i}.mp4")
    video_writer = imageio.get_writer(video_path, fps=20)
    demo = f'demo_{i}'
    idx=0
    print(demo,data['data'][demo]['obs']['agentview_image'].shape)
    for b in  data['data'][demo]['obs']['agentview_image']:
        img = Image.fromarray((b).astype(np.uint8))
        d = ImageDraw.Draw(img)
        d.text( (2,2), str(idx), fill=255)
        b = np.asarray(img)
        video_writer.append_data(b)
        idx+=1
    video_writer.close()
    Video(video_path, embed=True)


  0%|                                                                                                            | 0/1 [00:00<?, ?it/s]IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x563d92459fc0] Warning: data is not aligned! This can lead to a speed loss


demo_0 (48, 84, 84, 3)


100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.22it/s]


In [82]:
data['data']['demo_0']['obs'].keys()

<KeysViewHDF5 ['agentview_image', 'object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_eef_vel_ang', 'robot0_eef_vel_lin', 'robot0_eye_in_hand_image', 'robot0_gripper_qpos', 'robot0_gripper_qvel', 'robot0_joint_pos', 'robot0_joint_pos_cos', 'robot0_joint_pos_sin', 'robot0_joint_vel']>

In [110]:
data['data']['demo_0']['obs']['robot0_eef_quat'][0]

array([ 0.99657052, -0.00494504,  0.08251158,  0.00381968])

In [102]:
for i in range(48):
    print(data['data']['demo_0']['obs']['robot0_eef_pos'][i], data['data']['demo_0']['obs']['robot0_gripper_qpos'][i])
    print(data['data']['demo_0']['obs']['robot0_gripper_qpos'][i])
    print()

[-0.09460463 -0.00522699  1.02927228] [ 0.020833 -0.020833]
[ 0.020833 -0.020833]

[-0.09874985 -0.0062055   1.02457377] [ 0.02111628 -0.0211256 ]
[ 0.02111628 -0.0211256 ]

[-0.10049888 -0.00573117  1.02039571] [ 0.02310703 -0.02305081]
[ 0.02310703 -0.02305081]

[-0.09806703 -0.00545189  1.0158236 ] [ 0.02635937 -0.02636353]
[ 0.02635937 -0.02636353]

[-0.09255966 -0.00604606  1.00952064] [ 0.03037482 -0.03041996]
[ 0.03037482 -0.03041996]

[-0.08529666 -0.00734879  1.00209479] [ 0.03401951 -0.03409096]
[ 0.03401951 -0.03409096]

[-0.07682976 -0.00916491  0.99361215] [ 0.03618888 -0.03626456]
[ 0.03618888 -0.03626456]

[-0.06805754 -0.01166682  0.98462506] [ 0.03740217 -0.03748937]
[ 0.03740217 -0.03748937]

[-0.05932111 -0.01381672  0.97538432] [ 0.03810977 -0.03814793]
[ 0.03810977 -0.03814793]

[-0.0516081  -0.01558749  0.96589814] [ 0.03850119 -0.03852284]
[ 0.03850119 -0.03852284]

[-0.04495205 -0.01767185  0.9570293 ] [ 0.03870834 -0.03874494]
[ 0.03870834 -0.03874494]

[-0.038

In [73]:
imageabs = h5py.File('all_robomimic_data_combined.hdf5', 'r')
i=1
video_path = os.path.join('.', f"temp{i}.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
demo = f'demo_{i}'
idx=0
print(demo,imageabs['data'][demo]['obs']['agentview_image'].shape)
for b in  imageabs['data'][demo]['obs']['agentview_image']:
    img = Image.fromarray((b).astype(np.uint8))
    d = ImageDraw.Draw(img)
    d.text( (2,2), str(idx), fill=255)
    b = np.asarray(img)
    video_writer.append_data(b)
    idx+=1
video_writer.close()
Video(video_path, embed=True)
imageabs.close()

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


demo_1 (55, 84, 84, 3)


[swscaler @ 0x55d81d5cefc0] Warning: data is not aligned! This can lead to a speed loss


In [61]:
maxsf

313

In [65]:
# redcube = '/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/ph/image_abs.hdf5'
# print('redcube', h5py.File(redcube, 'r')['data'])
# allhammer = '/proj/vondrick3/sruthi/robots/diffusion_policy/1000alift_hammer_27_0_41_58.hdf5'
# print('allhammer', h5py.File(allhammer, 'r')['data'])
# cleanhammer = '/proj/vondrick3/sruthi/robots/diffusion_policy/1000galift_hammer_8_16_53_6_specific_stable.hdf5'
# print('cleanhammer', h5py.File(cleanhammer, 'r')['data'])
# allmug = '/proj/vondrick3/sruthi/robots/diffusion_policy/alift_mugbeige_9_0_33_24.hdf5'
# print('allmug', h5py.File(allmug, 'r')['data'])
# cleanmug = '/proj/vondrick3/sruthi/robots/diffusion_policy/alift_mugbeige_9_0_33_24_specific_stable.hdf5'
# print('cleanmug', h5py.File(cleanmug, 'r')['data'])
# combinedhammercube = '/proj/vondrick3/sruthi/robots/diffusion_policy/combined_200redcube_696hammer.hdf5'
# print('combinedhammercube', h5py.File(combinedhammercube, 'r')['data'])
# combinedhammercubemubegie = '/proj/vondrick3/sruthi/robots/diffusion_policy/combined_200redcube_696hammer_777mugbeige.hdf5'
# print('combinedhammercubemubegie', h5py.File(combinedhammercubemubegie, 'r')['data'])
all_paths = [
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_redcube_14_22_15_2/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_greencube_14_22_15_2/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_hammer_14_22_15_7/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugbeige_14_22_15_9/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugred_14_22_15_10/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_needle_14_22_15_14/',
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_squarenut_14_22_15_18/'
    '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_roundnut_14_22_15_18/'
]
for path in all_paths:
    print(path.split('/')[-2], h5py.File(path+path.split('/')[-2]+'.hdf5', 'r')['data'])




alift_redcube_14_22_15_2 <HDF5 group "/data" (859 members)>
alift_greencube_14_22_15_2 <HDF5 group "/data" (856 members)>
alift_hammer_14_22_15_7 <HDF5 group "/data" (696 members)>
alift_mugbeige_14_22_15_9 <HDF5 group "/data" (467 members)>
alift_mugred_14_22_15_10 <HDF5 group "/data" (926 members)>
alift_needle_14_22_15_14 <HDF5 group "/data" (721 members)>
alift_squarenut_14_22_15_18 <HDF5 group "/data" (76 members)>


In [ ]:
all_base_paths = [
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_redcube_14_22_15_2',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_greencube_14_22_15_2',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_hammer_14_22_15_7',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugbeige_14_22_15_9',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugred_14_22_15_10',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_needle_14_22_15_14',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_squarenut_14_22_15_18',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_roundnut_14_22_15_22'
]
for base_path in all_base_paths:
    base_path+='/'
    # base_path = '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_squarenut_14_22_15_22/'
    # base_path = '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.28/09.12.40_train_diffusion_unet_hybrid_combined_200redcube_696hammer/checkpoints/epoch=0200-test_mean_score=0.780/alift_mugbeige_9_0_33_24/'
    
    obsdict_agentview = np.load(base_path + 'obsdict_agentview.npy', allow_pickle=True)
    obsdict_agentview = (obsdict_agentview.transpose(0,2,1,4,5,3).reshape(13*8,1008,84,84,3)* 255.0).astype(np.uint8)[:-4]
    print('obsdict_agentview', obsdict_agentview.shape)
    
    obsdict_eyeinhand = np.load(base_path + 'obsdict_eyeinhand.npy', allow_pickle=True)
    obsdict_eyeinhand = (obsdict_eyeinhand.transpose(0,2,1,4,5,3).reshape(13*8,1008,84,84,3)* 255.0).astype(np.uint8)[:-4]
    print('obsdict_eyeinhand', obsdict_eyeinhand.shape)
    
    obsdict_robot0s = np.load(base_path + 'obsdict_robot0s.npy', allow_pickle=True)
    obsdict_robot0s = obsdict_robot0s.transpose(0,2,1,3).reshape(13*8,1008,9)[:-4]
    print('obsdict_robot0s', obsdict_robot0s.shape)
    
    actions = np.load(base_path + 'actions.npy', allow_pickle=True)
    actions = actions.transpose(0,2,1,3).reshape(13*8,1008,7)[:-4]
    print('actions', actions.shape)
    
    rewards = np.load(base_path + 'rewards.npy', allow_pickle=True)
    rewards = rewards.transpose(1,0)
    print('rewards', rewards.shape)
    
    oldstates = np.load(base_path + 'startstates.npy', allow_pickle=True)
    states = np.repeat(np.array(oldstates)[np.newaxis, :, :], obsdict_agentview.shape[0], axis=0)
    print('states', states.shape)
    
    grasping = np.load(base_path + 'grasping.npy', allow_pickle=True)
    grasping = grasping.transpose(1,0)
    print('grasping', grasping.shape)
    
    
    ''' CREATE 1 DATASET '''
    new_data = {'data':{}}
    
    count = 0
    for datapt in range(0,rewards.shape[1]):
        if len(np.argwhere(rewards[:,datapt]==1)) > 0:
            minz = min(np.argwhere(rewards[:,datapt]==1))[0]+16
            new_data['data'][f'demo_{count}'] = {
                'actions': actions[:minz, datapt],
                'obs': {
                    'agentview_image': obsdict_agentview[:minz, datapt],
                    'robot0_eye_in_hand_image': obsdict_eyeinhand[:minz, datapt],
                    'robot0_eef_pos': obsdict_robot0s[:minz, datapt, :3],
                    'robot0_eef_quat': obsdict_robot0s[:minz, datapt, 3:7],
                    'robot0_gripper_qpos': obsdict_robot0s[:minz, datapt, 7:],
                },
                'states': states[:minz,datapt,:]
            }
            # print(f'demo_{count}- {minz}')
            count+=1
    print(new_data['data'].keys())
    
    # Open HDF5 file and write in the data_dict structure and info
    savepath = base_path+base_path.split('/')[-2]+'.hdf5'
    f = h5py.File(savepath, 'w')
    datagrp = f.create_group('data')
    
    dataenvsargs = h5py.File('/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/ph/image_abs.hdf5', 'r')
    
    datagrp.attrs['env_args'] = dataenvsargs['data'].attrs['env_args']
    datagrp.attrs['total'] = len(new_data['data'])
    
    
    for demo in new_data['data']:
        demogrp = datagrp.create_group(demo)
        
        actionsdset = demogrp.create_dataset('actions', data = new_data['data'][demo]['actions'])
        # print('actions', actionsdset, new_data['data'][demo]['actions'])
        statesdset = demogrp.create_dataset('states', data = new_data['data'][demo]['states'])
    
        obsgrp = demogrp.create_group('obs') 
        for grp_name in new_data['data'][demo]['obs']:
            dset = obsgrp.create_dataset(grp_name, data = new_data['data'][demo]['obs'][grp_name])
            # print(grp_name, dset_name, new_data['data'][demo]['obs'][grp_name])
    f.close()


In [ ]:
696+777

In [ ]:
data = h5py.File('/proj/vondrick3/sruthi/robots/diffusion_policy/combined_200redcube_696hammer_777mugbeige.hdf5', 'r')
 
video_path = os.path.join('.', f"temp33.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
idx = 0
demo = 'demo_1402'
print(data['data'][demo]['obs']['agentview_image'].shape)
for b in  data['data'][demo]['obs']['agentview_image']:
    # for b in d:
    # b=b.transpose(1,2,0)
    print(b.shape)
    img = Image.fromarray((b).astype(np.uint8))
    d = ImageDraw.Draw(img)
    d.text( (2,2), str(idx), fill=255)
    
    #-- back to array
    b = np.asarray(img)

    video_writer.append_data(b)
    idx+=1
video_writer.close()
Video(video_path, embed=True)
# data.close()

In [4]:
f.close()

In [51]:
'''Combine Data'''
ogdata = h5py.File('/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/ph/image_abs.hdf5', 'r')
all_base_paths = [
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_redcube_14_22_15_2',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_greencube_14_22_15_2',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_hammer_14_22_15_7',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugbeige_14_22_15_9',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_mugred_14_22_15_10',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_needle_14_22_15_14',
# '/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_squarenut_14_22_15_18',
'/proj/vondrick3/sruthi/robots/diffusion_policy/data/outputs/2024.06.05/15.00.33_train_diffusion_unet_hybrid_liftph/checkpoints/epoch=0150-test_mean_score=0.980/alift_roundnut_14_22_15_22'
]

f = h5py.File('15.00.33_train_diffusion_unet_hybrid_liftph_200cube_73squarenut_alift_squarenut_14_22_15_18.hdf5', 'w')
datagrp = f.create_group('data')
datagrp.attrs['env_args'] = ogdata['data'].attrs['env_args']
index = 0
for demo in ogdata['data']:
    if ogdata['data'][demo]['states'].shape[0]==0:
        print(demo,'help')
    else:
        demogrp = datagrp.create_group(f'demo_{index}')
        index+=1
        
        actionsdset = demogrp.create_dataset('actions', data = ogdata['data'][demo]['actions'])
        statesdset = demogrp.create_dataset('states', data = ogdata['data'][demo]['states'])
    
        obsgrp = demogrp.create_group('obs') 
        for grp_name in ogdata['data'][demo]['obs']:
            dset = obsgrp.create_dataset(grp_name, data = ogdata['data'][demo]['obs'][grp_name])

for base_path in all_base_paths:
    datafile = base_path+'/'+base_path.split('/')[-1]+'.hdf5'
    data2 = h5py.File(datafile, 'r')
    
    for demo in data2['data']:
        if data2['data'][demo]['states'].shape[0]==0:
            print(demo,'help2')
        else:
            demogrp = datagrp.create_group(f'demo_{index}')
            index+=1
            
            actionsdset = demogrp.create_dataset('actions', data = data2['data'][demo]['actions'])
            statesdset = demogrp.create_dataset('states', data = data2['data'][demo]['states'])
        
            obsgrp = demogrp.create_group('obs') 
            for grp_name in data2['data'][demo]['obs']:
                dset = obsgrp.create_dataset(grp_name, data = data2['data'][demo]['obs'][grp_name])

datagrp.attrs['total'] = index
f.close()

In [54]:
data = h5py.File('15.00.33_train_diffusion_unet_hybrid_liftph_200cube_50roundnut_alift_roundnut_14_22_15_22.hdf5', 'r')
print(data['data'])
for i in range(200,250,10):
    video_path = os.path.join('.', f"temp{i}.mp4")
    video_writer = imageio.get_writer(video_path, fps=20)
    idx = 0
    demo = f'demo_{i}'
    print(data['data'][demo]['obs']['agentview_image'].shape)
    
    for b in  data['data'][demo]['obs']['agentview_image']:
        # for b in d:
        # b=b.transpose(1,2,0)
        print(b.shape)
        img = Image.fromarray((b).astype(np.uint8))
        d = ImageDraw.Draw(img)
        d.text( (2,2), str(idx), fill=255)
        
        #-- back to array
        b = np.asarray(img)
    
        video_writer.append_data(b)
        idx+=1
    video_writer.close()
    Video(video_path, embed=True)
data.close()

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


<HDF5 group "/data" (253 members)>
(78, 84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)


[swscaler @ 0x55d15fd2bfc0] Warning: data is not aligned! This can lead to a speed loss
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(100, 84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)


[swscaler @ 0x558fd0fe3fc0] Warning: data is not aligned! This can lead to a speed loss


(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)


IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(100, 84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)


[swscaler @ 0x55a860475fc0] Warning: data is not aligned! This can lead to a speed loss


(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84,

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


(80, 84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)


[swscaler @ 0x55ceaf206fc0] Warning: data is not aligned! This can lead to a speed loss
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (84, 84) to (96, 96) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).


(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(100, 84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)
(84, 84, 3)

[swscaler @ 0x5557c297afc0] Warning: data is not aligned! This can lead to a speed loss


In [ ]:
avg = []
for root, subdirs, files in os.walk('/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/'):
    for file in files:
        if 'pick_place' in file and 'hdf5' in file and 'lock' not in file and 'zip' not in file and 'abs' not in file:
            print(root,subdirs,file)
            data = h5py.File(os.path.join(root,file), 'r')
            print(data['data'])
            for demo in data['data']:
                # print(demo)
                avg.append(data['data'][demo]['actions'].shape[0])
print(sum(avg)/len(avg))

In [ ]:
h5py.File('/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/pick_place_d0.hdf5', 'r')['data']['demo_30']['states']

In [ ]:
#hdf5 file /proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/tool_hang/ph/image_abs.hdf5 has 200 demonstrations
f["data"]['demo_0'].keys() # <KeysViewHDF5 ['actions', 'dones', 'next_obs', 'obs', 'rewards', 'states']>
f["data"]['demo_0']['actions'].shape #(681, 7)
f["data"]['demo_0']['dones'].shape #(681, )
f["data"]['demo_0']['rewards'].shape #(681, )
f["data"]['demo_0']['states'].shape #(681, 58)
f["data"]['demo_0']['next_obs'].keys() #<KeysViewHDF5 ['object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_eef_vel_ang', 'robot0_eef_vel_lin', 'robot0_eye_in_hand_image', 'robot0_gripper_qpos', 'robot0_gripper_qvel', 'robot0_joint_pos', 'robot0_joint_pos_cos', 'robot0_joint_pos_sin', 'robot0_joint_vel', 'sideview_image']>
f["data"]['demo_0']['next_obs']['object']# (681, 44)
f["data"]['demo_0']['next_obs']['robot0_eef_pos']# (681, 3)
f["data"]['demo_0']['next_obs']['robot0_eef_pos']# (681, 44)
f["data"]['demo_0']['next_obs']['robot0_eef_quat']# (681, 4)
f["data"]['demo_0']['next_obs']['robot0_eef_vel_ang']# (681, 3)
f["data"]['demo_0']['next_obs']['robot0_eef_vel_lin']# (681, 3)
f["data"]['demo_0']['next_obs']['robot0_eye_in_hand_image']# (681, 240, 240, 3)
f["data"]['demo_0']['next_obs']['robot0_gripper_qpos']# (681, 2)
f["data"]['demo_0']['next_obs']['robot0_gripper_qvel']# (681, 2)
f["data"]['demo_0']['next_obs']['robot0_joint_pos']# (681, 7)
f["data"]['demo_0']['next_obs']['robot0_joint_pos_cos']# (681, 7)
f["data"]['demo_0']['next_obs']['robot0_joint_pos_sin']# (681, 7)
f["data"]['demo_0']['next_obs']['robot0_joint_vel']# (681, 7)
f["data"]['demo_0']['next_obs']['sideview_image']# (681, 240, 240, 3)

# hdf5 file /proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/square_d0.hdf5 has 1000 demonstrations
f["data"].keys() # <HDF5 group "/data" (1000 members)>
f["data"]['demo_0'].keys() # <KeysViewHDF5 ['actions', 'dones', 'obs', 'rewards', 'states']>
f["data"]['demo_0']['actions'].shape #(136, 7)
f["data"]['demo_0']['dones'].shape #(136, )
f["data"]['demo_0']['rewards'].shape #(136, ) 
f["data"]['demo_0']['states'].shape #(136, 45)
f["data"]['demo_0']['next_obs'].keys() # <KeysViewHDF5 ['agentview_image', 'object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_eef_vel_ang', 'robot0_eef_vel_lin', 'robot0_eye_in_hand_image', 'robot0_gripper_qpos', 'robot0_gripper_qvel', 'robot0_joint_pos', 'robot0_joint_pos_cos', 'robot0_joint_pos_sin', 'robot0_joint_vel']>
f["data"]['demo_0']['next_obs']['object']# (136, 14)
f["data"]['demo_0']['next_obs']['agentview_image']# (136, 84, 84, 3)
f["data"]['demo_0']['next_obs']['robot0_eef_pos']# (136, 3)

In [ ]:
def generate_view_video(fname, data, view):
    demo_folder = 'demo_5'
    video_path = os.path.join('.', f"start_{fname}_{task}_{demo_folder}_{view}.mp4")
    video_writer = imageio.get_writer(video_path, fps=20)
    for video_img in data["data"][demo_folder]['obs'][view]:
        video_writer.append_data(video_img)
    video_writer.close()
    Video(video_path, embed=True)
generate_view_video('source', f_source, 'agentview_image')

In [ ]:
def task_reset_dist(fname, data, view, name):
    demo_folder = 'demo_5'
    video_path = os.path.join('.', f"resets_{name}.mp4")
    video_writer = imageio.get_writer(video_path, fps=20)
    for demo_folder in data['data']:
        video_writer.append_data(data["data"][demo_folder]['obs'][view][0])
    video_writer.close()
    Video(video_path, embed=True)

In [ ]:
path = f'/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/square/ph/image_abs.hdf5'
task_reset_dist('interp', h5py.File(path, "r"), 'agentview_image', 'robomimic_square_ph_image_abs')

In [ ]:
data = h5py.File(f'./data/robomimic/datasets/square/ph/image_abs.hdf5', "r")
data['data'].keys()
demo_folder = 'demo_100'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/source/stack_three.hdf5', "r")
print(data['data'])
demo_folder = 'demo_30'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/coffee_preparation_d1.hdf5', "r")
print(data['data'])
demo_folder = 'demo_30'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/coffee_preparation_d1.hdf5', "r")
print(data['data'])
demo_folder = 'demo_5'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/kitchen_d1.hdf5', "r")
print(data['data'])
demo_folder = 'demo_5'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data["data"][demo_folder].keys()

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/ph/image_abs.hdf5', "r")
print(data['data'])
demo_folder = 'demo_5'
video_path = os.path.join('.', f"temp.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
video_writer.close()
Video(video_path, embed=True)

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/core/stack_three_d1.hdf5', "r")
video_path = os.path.join('.', f"tdist.mp4")
video_writer = imageio.get_writer(video_path, fps=20)
for demo_folder in data['data']:
    video_writer.append_data(data["data"][demo_folder]['obs']['agentview_image'][0])
    print(data["data"][demo_folder]['obs']['agentview_image'][0].shape)
video_writer.close()
Video(video_path, embed=True)
# print(video_path)

In [ ]:
os.listdir('/proj/vondrick3/sruthi/robots/mimicgen_environments/datasets/large_interpolation/')

In [ ]:
data = h5py.File(f'/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/ph/image_abs.hdf5', "r")
for demo in data["data"]:
    video_path = os.path.join('.', f"/proj/vondrick3/sruthi/robots/diffusion_policy/data/robomimic/datasets/lift/phvids/{demo}.mp4")
    video_writer = imageio.get_writer(video_path, fps=20)
    i=0
    video_img= data["data"][demo]['obs']['agentview_image'][0]
    video_writer.append_data(np.zeros_like(video_img))
    video_writer.append_data(np.zeros_like(video_img))
    video_writer.append_data(np.zeros_like(video_img))
    video_writer.append_data(np.zeros_like(video_img))
    video_writer.append_data(np.zeros_like(video_img))
    print(video_img.shape)
    for video_img in data["data"][demo]['obs']['agentview_image']: #robot0_eye_in_hand_image
        if i%5==0:
            video_writer.append_data(video_img)
        i+=1
    video_writer.close()
    Video(video_path, embed=True)
    # print(video_path)